name: 05-Build with Metadata

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
#     Enable building against a wider range of platforms.
#       - name: Docker Setup QEMU
#         uses: docker/setup-qemu-action@v2.1.0
   
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#       New:Docker MetaData
      - name: Docker Meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with: 
          images: gmshuvo/docker-ci-automation
          flavor: |
            latest=false
          tag: |
            type=raw,value=04
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}
#       New(end)

      - name: Docker build
        uses: docker/build-push-action@v4
        with:
#           push: ${{ github.event_name != 'pull_request' }}
#           tags: gmshuvo/docker-ci-automation:latest,gmshuvo/docker-ci-automation:03

#           NEW(Start)
            push: true
            tags: ${{steps.docker_meta.outputs.tags}}
            labels: ${{steps.docker_meta.outputs.lables}}
#           NEW(end)

            cache-from: type=gha
            cache-to: type=gha,mode=max
  #           define platforms
#             platforms: linux/amd64,linux/arm64,linux/arm/v7
